server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/heima?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      # 根据创建表 emmm
      ddl-auto: none
    # 控制台打印sql
    show-sql: true
    database: mysql

  elasticsearch:
    username: elastic
    password: oAyhj3+TUZGXn00C-GIF
    uris:
      - http://localhost:9201
logging:
  level:
    com.wjl.hotel3: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.wjl.hotel3.pojo
